-- vim.api.nvim_create_autocmd('PackChanged', {
--   callback = function(ev)
--     local name, kind = ev.data.spec.name, ev.data.kind
--     if kind ~= 'install' and kind ~= 'update' then return end
--     if name == 'telescope-fzf-native.nvim' then
--       -- block so the .so is ready before plugin/telescope.lua runs load_extension
--       vim.system({ 'make' }, { cwd = ev.data.path }):wait()
--     end
--     if name == 'LuaSnip' then
--       vim.system({ 'make', 'install_jsregexp' }, { cwd = ev.data.path })
--     end
--   end,
-- })
-- 
-- 
-- local gh = function(x) return 'https://github.com/' .. x end
-- 
-- vim.pack.add({
--   -- telescope
--   gh('nvim-telescope/telescope.nvim'),
--   gh('nvim-telescope/telescope-fzf-native.nvim'),
--   gh('nvim-lua/plenary.nvim'),
-- 
--   -- lsp / completion
--   gh('hrsh7th/nvim-cmp'),
--   gh('hrsh7th/cmp-nvim-lsp'),
--   gh('hrsh7th/cmp-buffer'),
--   gh('hrsh7th/cmp-path'),
--   gh('j-hui/fidget.nvim'),
-- 
--   -- snippets
--   { src = gh('L3MON4D3/LuaSnip'), version = vim.version.range('>=2.0, <3.0') },
--   gh('saadparwaiz1/cmp_luasnip'),
-- 
--   -- formatting
--   gh('stevearc/conform.nvim'),
-- 
--   -- navigation
--   gh('ThePrimeagen/harpoon'),
-- 
--   -- utils
--   gh('laytan/cloak.nvim'),
--   gh('ThePrimeagen/vim-be-good'),
-- })
-- 
-- require("pde.plugins.cloak")
-- require("pde.plugins.harpoon")
-- require("pde.plugins.conform")
-- require("pde.plugins.telescope")
-- require("pde.plugins.lsp")
-- require("pde.plugins.snippets")
